elasticsearch:
  serverUrl: http://localhost:9200
  apiKey: bTRReWFaVUJzYnB2TkJ3QXNVd1c6b0g3VGpXUlBUTmVBTWFDWXk0LW1rUQ==

opensearch:
  serverUrl: http://127.0.0.1:9200
  username: admin
  password: admin

spring:
  batch.job.enabled: false
  profiles:
    include:
      - "api"
  application.name: bookspot-batch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BookSpot?rewriteBatchedStatements=true&allowLoadLocalInfile=true
    hikari:
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  server:
    port: 9292 # 해당 포트 접근하면 서버의 정보를 다 알 수 있음 - 보안 관련 설정
  endpoint:
    health:
      # db, disk, ping 등등 자세한 정보를 볼 수 있도록 만드는 설정
      show-details: always #  status(UP or DOWN)를 포함한 디테일한 숫자정보
  endpoints:
    web:
      base-path: /my-monitor # '...:9292/my-monitor'로 요청
      exposure:
        include: "*" # 모든 엔드포인트 노출

path:
  directory:
    root: C:/Programming_Tools/temp_bookSpotFiles
    librarySync: ${path.directory.root}/librarySync
    bookSync: ${path.directory.root}/bookSync
    stockSync: ${path.directory.root}/bookSync
    loanSync: ${path.directory.root}/bookSync
    normalizedStock: ${path.directory.root}/normalizedStock
    filteredStock: ${path.directory.root}/filteredStock
    deletedStock: ${path.directory.root}/deletedStock
  #    stockSync: ${path.directory.root}/stockSync
  #    loanSync: ${path.directory.root}/loanSync
  file:
    library: ${path.directory.librarySync}/library_list.xlsx
    loan: ${path.directory.root}/aggregated/unique_books.csv
