spring:
  profiles:
    include:
      - "api"
  application.name: bookspot-batch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BookSpot?rewriteBatchedStatements=true
    hikari:
      username: root
      password: 1234